export type ReviewedClassificationConfidence = "high" | "medium" | "low";

interface CodeLike {
  code: string;
  system?: string;
  source_area_codes?: string[];
}

interface FTermThemeLike {
  aspects: CodeLike[];
}

interface FiSubdivisionLike {
  fi: CodeLike;
  parent_area_codes: string[];
  f_term_themes: FTermThemeLike[];
}

interface ClassificationRouteLike {
  ipc_cpc_area: CodeLike[];
  fi_subdivisions: FiSubdivisionLike[];
}

interface ReviewedDomainKeywordLike {
  ipc: string[];
  cpc: string[];
  fi: string[];
  f_term: string[];
  ipc_evidence?: CodeLike[];
  cpc_evidence?: CodeLike[];
  fi_evidence?: CodeLike[];
  f_term_evidence?: CodeLike[];
  ipc_candidates?: CodeLike[];
  cpc_candidates?: CodeLike[];
  fi_candidates?: CodeLike[];
  f_term_candidates?: CodeLike[];
  classification_route?: ClassificationRouteLike;
  classification_confidence: ReviewedClassificationConfidence;
  classification_reason: string;
}

interface ReviewedDomainResultLike {
  keywords: ReviewedDomainKeywordLike[];
}

const DOMAIN_PASSED_REASON =
  "Classification candidates were retrieved from Supabase, passed technical-context scoring, and remained inside the final AI-reviewed document classification domain. No model-generated classification code was accepted.";

const DOMAIN_WITHHELD_REASON =
  "Catalog candidates were withheld because they fell outside the final AI-reviewed document classification domain. Classification codes were left empty rather than exposing remote lexical matches.";

const NO_CATALOG_MATCH_REASON =
  "No Supabase classification record passed the technical-context threshold. Classification codes were left empty rather than generated by AI.";

function normalizeClassificationCode(code: string): string {
  return code.normalize("NFKC").toUpperCase().replace(/[^A-Z0-9]/g, "");
}

function classificationMainGroupKey(code: string): string {
  const normalized = code
    .normalize("NFKC")
    .toUpperCase()
    .replace(/[^A-Z0-9/]/g, "");
  const match = normalized.match(/^([A-H]\d{2}[A-Z])(\d+)/u);
  return match ? `${match[1]}${match[2]}` : "";
}

export function reviewedCpcMainGroups(classificationQuery: string): string[] {
  const groups = new Set<string>();
  const pattern = /CPC\s*=\s*([A-H]\d{2}[A-Z]\s*\d+(?:\s*\/\s*\d+)?)/giu;

  for (const match of classificationQuery.matchAll(pattern)) {
    const group = classificationMainGroupKey(match[1]);
    if (group) groups.add(group);
  }

  return Array.from(groups).sort((a, b) => a.localeCompare(b));
}

function codeIsInReviewedDomain(code: string, allowedMainGroups: Set<string>): boolean {
  const group = classificationMainGroupKey(code);
  return Boolean(group) && allowedMainGroups.has(group);
}

function evidenceCount(keyword: ReviewedDomainKeywordLike): number {
  return [
    ...(keyword.ipc_evidence ?? []),
    ...(keyword.cpc_evidence ?? []),
    ...(keyword.fi_evidence ?? []),
    ...(keyword.f_term_evidence ?? []),
  ].length;
}

/**
 * Makes every displayed IPC/CPC/FI/F-term route agree with the CPC domains
 * selected by the structured AI query review. The reviewed query can retain
 * multiple main groups for a genuinely cross-domain invention. When no CPC
 * domain was selected, the existing catalog-backed classifications are left
 * unchanged rather than being erased.
 */
export function applyReviewedClassificationDomainGate<
  T extends ReviewedDomainResultLike,
>(result: T, classificationQuery: string): T {
  const allowedMainGroups = new Set(reviewedCpcMainGroups(classificationQuery));

  if (allowedMainGroups.size === 0) return result;

  for (const keyword of result.keywords) {
    const beforeCount = evidenceCount(keyword);

    keyword.ipc_candidates = (keyword.ipc_candidates ?? []).filter((candidate) =>
      codeIsInReviewedDomain(candidate.code, allowedMainGroups)
    );
    keyword.cpc_candidates = (keyword.cpc_candidates ?? []).filter((candidate) =>
      codeIsInReviewedDomain(candidate.code, allowedMainGroups)
    );
    keyword.ipc_evidence = (keyword.ipc_evidence ?? []).filter((evidence) =>
      codeIsInReviewedDomain(evidence.code, allowedMainGroups)
    );
    keyword.cpc_evidence = (keyword.cpc_evidence ?? []).filter((evidence) =>
      codeIsInReviewedDomain(evidence.code, allowedMainGroups)
    );
    keyword.ipc = keyword.ipc_evidence.map((evidence) => evidence.code);
    keyword.cpc = keyword.cpc_evidence.map((evidence) => evidence.code);

    const route = keyword.classification_route ?? {
      ipc_cpc_area: [],
      fi_subdivisions: [],
    };
    const retainedAreas = route.ipc_cpc_area.filter((area) =>
      codeIsInReviewedDomain(area.code, allowedMainGroups)
    );
    const retainedAreaCodes = new Set(
      retainedAreas.map((area) => normalizeClassificationCode(area.code)),
    );
    const retainedFiSubdivisions = route.fi_subdivisions
      .map((subdivision) => ({
        ...subdivision,
        parent_area_codes: subdivision.parent_area_codes.filter((code) =>
          retainedAreaCodes.has(normalizeClassificationCode(code))
        ),
      }))
      .filter((subdivision) => subdivision.parent_area_codes.length > 0);
    const retainedFiCodes = new Set(
      retainedFiSubdivisions.map((subdivision) =>
        normalizeClassificationCode(subdivision.fi.code)
      ),
    );
    const retainedFTermCodes = new Set(
      retainedFiSubdivisions.flatMap((subdivision) =>
        subdivision.f_term_themes.flatMap((theme) =>
          theme.aspects.map((aspect) => normalizeClassificationCode(aspect.code))
        )
      ),
    );

    keyword.fi_candidates = (keyword.fi_candidates ?? []).filter((candidate) =>
      retainedFiCodes.has(normalizeClassificationCode(candidate.code)) ||
      (candidate.source_area_codes ?? []).some((code) =>
        retainedAreaCodes.has(normalizeClassificationCode(code))
      )
    );
    keyword.fi_evidence = (keyword.fi_evidence ?? []).filter((evidence) =>
      retainedFiCodes.has(normalizeClassificationCode(evidence.code))
    );
    keyword.fi = keyword.fi_evidence.map((evidence) => evidence.code);
    keyword.f_term_candidates = (keyword.f_term_candidates ?? []).filter(
      (candidate) =>
        retainedFTermCodes.has(normalizeClassificationCode(candidate.code)),
    );
    keyword.f_term_evidence = (keyword.f_term_evidence ?? []).filter((evidence) =>
      retainedFTermCodes.has(normalizeClassificationCode(evidence.code))
    );
    keyword.f_term = keyword.f_term_evidence.map((evidence) => evidence.code);
    keyword.classification_route = {
      ipc_cpc_area: retainedAreas,
      fi_subdivisions: retainedFiSubdivisions,
    };

    const afterCount = evidenceCount(keyword);
    keyword.classification_confidence =
      keyword.fi.length > 0 && keyword.f_term.length > 0
        ? "high"
        : afterCount > 0
          ? "medium"
          : "low";
    keyword.classification_reason =
      afterCount > 0
        ? DOMAIN_PASSED_REASON
        : beforeCount > 0
          ? DOMAIN_WITHHELD_REASON
          : NO_CATALOG_MATCH_REASON;
  }

  return result;
}
