create table if not exists public.patent_search_insights (
  id bigint generated by default as identity primary key,
  display_order smallint not null unique check (display_order > 0),
  title text not null,
  body text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

comment on table public.patent_search_insights is
  'Curated patent-search insights displayed to signed-in users while an analysis is running.';

alter table public.patent_search_insights enable row level security;

revoke all on table public.patent_search_insights from anon, authenticated;
grant select on table public.patent_search_insights to authenticated;

drop policy if exists "Authenticated users can read active patent search insights"
  on public.patent_search_insights;

create policy "Authenticated users can read active patent search insights"
  on public.patent_search_insights
  for select
  to authenticated
  using (is_active);

insert into public.patent_search_insights (display_order, title, body)
values
  (1, 'Claims matter more than titles or abstracts.', 'Patentability, infringement, invalidity, and freedom-to-operate analysis ultimately depend heavily on claim language.'),
  (2, 'Do not search only the inventor''s terminology.', 'Different applicants can describe the same technical concept using substantially different words.'),
  (3, 'Combine keyword and classification searching.', 'Keywords provide semantic flexibility, while IPC, CPC, FI, and F-term classifications provide technical structure.'),
  (4, 'Begin with the technical concept, not the search query.', 'Decompose the invention into its purpose, object, components, relationships, operation, control, conditions, and technical effects before constructing queries.'),
  (5, 'Search concepts separately before combining them.', 'An overly narrow Boolean query can hide highly relevant references; establish useful concept sets first, then combine them progressively.'),
  (6, 'Synonym expansion is essential.', 'A single concept may appear under engineering, legal, commercial, historical, or product-specific terminology.'),
  (7, 'Search functional language.', 'Functional descriptions such as configured to, adapted to, responsive to, and equivalent wording can reveal patents that use different structural terminology.'),
  (8, 'Search the problem as well as the solution.', 'Prior art may describe the same technical problem while implementing a different solution that still provides a valuable search path.'),
  (9, 'Search the technical effect.', 'Effects such as reducing latency, suppressing noise, lowering power consumption, or improving alignment can expose closely related inventions.'),
  (10, 'Search components and relationships separately.', 'Common components may be unremarkable individually, while the relationship among them contains the inventive concept.'),
  (11, 'Relationships are often more discriminative than nouns.', 'A relationship such as A controls B based on C can be more valuable than searching A, B, and C independently.'),
  (12, 'Search operating conditions.', 'Temperature, frequency, timing, pressure, geometry, state, environment, and operating mode can distinguish relevant prior art.'),
  (13, 'Use CPC subclasses as search neighborhoods, not absolute truth.', 'Classification assignments are useful but incomplete and sometimes inconsistent, so related classes should be explored rather than treated as hard boundaries.'),
  (14, 'Read classification definitions and notes.', 'The apparent meaning of an IPC or CPC symbol may differ from its formal scope, exclusions, precedence rules, and references.'),
  (15, 'Follow classification references.', 'See-also references, precedence rules, residual groups, and neighboring subclasses can reveal overlooked prior art.'),
  (16, 'Search both broad and narrow classifications.', 'Narrow codes improve precision, while broader parent classes improve recall and expose alternative classification choices.'),
  (17, 'Treat Japanese FI and F-term searching as a complementary layer.', 'FI and F-term can expose Japanese technical distinctions that IPC or CPC searches may not isolate efficiently.'),
  (18, 'Search patent families, not documents in isolation.', 'Different family members may contain clearer claims, better translations, additional drawings, examiner citations, or more useful procedural history.'),
  (19, 'The earliest priority date is critical.', 'Priority date, filing date, publication date, and grant date answer different legal and search questions and should never be treated as interchangeable.'),
  (20, 'Publication date determines public availability at a particular time.', 'An early priority date alone does not necessarily mean the disclosed information was publicly accessible on that date.'),
  (21, 'Backward citations are powerful prior-art leads.', 'Earlier references cited by a patent can reveal technologies considered relevant during drafting, searching, or examination.'),
  (22, 'Forward citations expose later technical evolution.', 'Later patents that cite a reference can identify follow-on inventions, competitors, alternative implementations, and emerging terminology.'),
  (23, 'Examiner citations can be particularly informative.', 'Examiner-added references often indicate documents considered technically or legally relevant during examination.'),
  (24, 'Citation searching should become iterative.', 'Relevant patents lead to classifications, inventors, assignees, terminology, family members, and further citations that should influence the next search round.'),
  (25, 'Inventor and assignee searching can uncover hidden clusters.', 'Organizations and inventors frequently reuse technical concepts while changing terminology across applications and generations of technology.'),
  (26, 'Search non-patent literature when appropriate.', 'Papers, standards, manuals, product documentation, theses, conference materials, and archived webpages may provide important technical disclosures.'),
  (27, 'For validity searching, use the claim limitation as a basic search unit.', 'Breaking a claim into required limitations makes it easier to locate evidence and assess whether the necessary disclosure exists in legally relevant references.'),
  (28, 'For FTO searching, focus on live claims in relevant jurisdictions.', 'An old technical disclosure may be useful background but irrelevant to current infringement risk if no enforceable claim covers the contemplated activity.'),
  (29, 'Search stopping criteria should be explicit.', 'A search is rarely complete; it should end according to predefined coverage, quality, time, budget, or diminishing-return criteria.'),
  (30, 'The best search is an evidence-building process, not a query-building process.', 'High-quality patent searching progressively builds a defensible map connecting concepts, classifications, families, claims, citations, dates, legal status, and supporting evidence.')
on conflict (display_order) do update
set
  title = excluded.title,
  body = excluded.body,
  is_active = true;
